language: minimal
services:
  - docker

script:
  - git submodule init
  - git submodule update
  - docker-compose up build

deploy:
  - provider: script
    script: bash ./.scripts/deploy.sh
    skip_cleanup: true
    on:
      branch: source # or master if you are using the two-repository approach
