baseURL: https://klinki.github.io/
disablePathToLower: false

title: Klinki's code blog
theme: mainroad
displayauthor: false

languageCode: en
defaultContentLanguage: en
defaultContentLanguageInSubdir: false

pygmentsUseClasses: true
pygmentsCodeFences: true

disqusShortname: klinki
googleAnalytics: UA-89466580-1
comments: true

markup:
  defaultMarkdownHandler: goldmark
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: false
    noClasses: true
    noHl: false
    style: monokai
    tabWidth: 4

languages:
  cs:
    contentDir: content/cs
    languageName: Čeština
    params:
      navigation:
        about: O mne
    menu:
      main:
        - identifier: about
          url: "/cs/o-mne"
          name: "O mně"

        - identifier: blog
          url: "/cs/blog"
          name: "Blog"

  en:
    contentDir: content/en
    languageName: English
    menu:
      main:
        - identifier: about
          url: "/about"
          name: "About"

        - identifier: blog
          url: "/blog"
          name: "Blog"

frontmatter:
  date:
    - ":filename:"
    - ":default"

  title:
    - ":filename"
    - ":default"

  comments: true

permalinks:
  blog: /blog/:slug
  pages: /:filename

params:
  navigation:
    about: About
  description: Software Developer
  displayauthor: false
  sidebar:
    home: right
    list: right
    single: true
    widgets:
      - search
      - recent
      - categories
      - taglist
      - social
      - languages
  mainSections:
    - blog
  widgets:
    tags_counter: true
    social:
      twitter: klinkicz
      linkedin: davidklingenberg
      github: klinki
  customCss:
    - css/syntax.css
# useFilenameDateAsFallback: true

taxonomies:
  tag: "tags"
  category: "categories"
  blog: "posts"

links:
  Home : "/"
  Blog: "/blog/"
  About: "/about/"
