version: "2"
services:
  hugo:
    image: klakegg/hugo:0.101.0
    command: server -DF --disableFastRender
    volumes:
      - ./:/src
    ports:
      - 1313:1313
  build:
    image: klakegg/hugo:0.101.0
    volumes:
      - .:/src
      - ./public:/target
